force-app/main/default/objects/Joke__c/Joke__c.object-meta.xml
<CustomObject>
    <description>Jokes from the https://icanhazdadjoke.com/</description>
    <label>Joke</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Joke Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jokes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Joke__c/fields/Joke__c.field-meta.xml
<CustomField>
    <fullName>Joke__c</fullName>
    <label>Joke</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Joke__c/fields/Joke_Id__c.field-meta.xml
<CustomField>
    <fullName>Joke_Id__c</fullName>
    <externalId>true</externalId>
    <label>Joke Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScheduledJoke.cls
public class ScheduledJoke implements Schedulable, Database.AllowsCallouts {

    public static String CRON_EXP = '0 15 * * * ?';

    public void execute(SchedulableContext SC) {
        requestData();
   	}
    
    public static HTTPResponse requestData(){
        HttpRequest request = new HttpRequest();
        // get this value from Setup -> Named Credentials
        request.setEndpoint('callout:icanhazdadjoke');
        request.setMethod('GET');
        request.setHeader('Accept', 'application/json');
        HTTPResponse response = new HTTPResponse();
        try {
            response = new Http().send(request);
            String body = response.getBody();
            System.debug(body);
            Map<String, Object> mapResp = (Map<String, Object>)JSON.deserializeUntyped(body);
            String jokeId = null;
            if (mapResp.containsKey('id')){
                jokeId = (String)mapResp.get('id');
                List<Joke__c> oldJokes = [SELECT Id FROM Joke__c WHERE Joke_Id__c  = :jokeId];
                if (oldJokes.isEmpty()){
                    insert new Joke__c(Joke_Id__c = (String)mapResp.get('id'), Joke__c = (String)mapResp.get('joke'));
                }
            }
        } catch(Exception e){
            response.setStatusCode(000);
            response.setStatus('Exception');
            response.setBody('{"Error":"'+e.getMessage()+'"}');
            System.debug(e.getMessage());
            new Logger().log(e).saveLogs();
        }
        return response;
    }
    
}