force-app/main/default/objects/Solar_Day__c/Solar_Day__c.object-meta.xml
<CustomObject>
    <label>Solar Day</label>
    <nameField>
        <displayFormat>SD-{00000}</displayFormat>
        <label>Solar Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solar Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Solar_Day__c/fields/Power__c.field-meta.xml
<CustomField>
    <fullName>Power__c</fullName>
    <label>Power</label>
    <summarizedField>Solar_Energy__c.Power__c</summarizedField>
    <summaryForeignKey>Solar_Energy__c.Solar_Day__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Solar_Energy__c/Solar_Energy__c.object-meta.xml
<CustomObject>
    <label>Solar Energy</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Solar Energy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solar Energies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solar_Energy__c/fields/Current__c.field-meta.xml
<CustomField>
    <fullName>Current__c</fullName>
    <label>Current (A)</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solar_Energy__c/fields/Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_Time__c</fullName>
    <label>Date Time</label>
    <length>26</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Solar_Energy__c/fields/Power__c.field-meta.xml
<CustomField>
    <fullName>Power__c</fullName>
    <formula>(Voltage__c *  Current__c) / 60.0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Power (W)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solar_Energy__c/fields/Solar_Day__c.field-meta.xml
<CustomField>
    <fullName>Solar_Day__c</fullName>
    <label>Solar Day</label>
    <referenceTo>Solar_Day__c</referenceTo>
    <relationshipLabel>Solar Energies</relationshipLabel>
    <relationshipName>Solar_Energies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Solar_Energy__c/fields/Voltage__c.field-meta.xml
<CustomField>
    <fullName>Voltage__c</fullName>
    <label>Voltage (V)</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SolarEnergyService.cls
@RestResource(urlMapping='/solarenergy/*')
global with sharing class SolarEnergyService {


    @HttpGet
    global static void getSolarEnergy() {
        RestRequest request = RestContext.request;
        RestResponse response = RestContext.response;
        try {
            String solarEnergyId = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
            List<Solar_Energy__c> energies = [
                SELECT Id, Name, Solar_Day__c, Power__c, Date_Time__c, Current__c, Voltage__c 
                FROM Solar_Energy__c 
                WHERE Id  = :solarEnergyId
            ];
            Solar_Energy__c solarEnergy;
            if (!energies.isEmpty()) {
                solarEnergy = energies.get(0);
            }
            // return solarEnergy;
            response.responseBody = Blob.valueOf(JSON.serialize(solarEnergy));
            response.statusCode = 200;
            // Integer i = 25 / 0;
        } catch (Exception e) {
            response.responseBody = Blob.valueOf(e.getMessage());
            response.statusCode = 500;
        }
        // return null;
    }

	@HttpPost
    global static String createEnergyRecord(String timestamp, String voltage, String current) {
        Map<String,Object> result = new Map<String,Object>();

        try {
            Datetime convertedTimestamp = Datetime.valueOf(timestamp.replace('T', ' '));
            System.debug(convertedTimestamp);
    
            Date currentDate = convertedTimestamp.date();
            List<Solar_Day__c> solarDays = [SELECT Id FROM Solar_Day__c WHERE Date__c  = :currentDate];
            System.debug(solarDays);
    
            Solar_Day__c currentSolarDay;
            if (solarDays.isEmpty()) {
                currentSolarDay = new Solar_Day__c(Date__c = currentDate);
                insert currentSolarDay;
            } else {
                currentSolarDay = solarDays.get(0);
            }
            System.debug(currentSolarDay);
            Solar_Energy__c energy = new Solar_Energy__c();
            energy.Date_Time__c = timestamp;
            energy.Solar_Day__c = currentSolarDay.Id;
            energy.Timestamp__c = convertedTimestamp;
            energy.Voltage__c = Double.valueOf(voltage);
            energy.Current__c = Double.valueOf(current);
            System.debug(energy);
            Database.SaveResult saveResult = Database.insert(energy, false);
            System.debug(saveResult);
            if (saveResult.isSuccess()) {
                result.put('Id', energy.Id);
                result.put('timestamp', timestamp);
                result.put('isSuccess', true);
            } else {
                result.put('isSuccess', false);
                result.put('Errors', saveResult.getErrors());
            }
            return JSON.serialize(result);
        } catch(Exception exp) {
            result.put('isSuccess', false);
            result.put('Errors', exp.getMessage());
            return JSON.serialize(result);
        }
    }
}