force-app/main/default/objects/Cryptocurrency__c/Cryptocurrency__c.object-meta.xml
<CustomObject>
    <label>Cryptocurrency</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Cryptocurrency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cryptocurrencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cryptocurrency__c/fields/Tether_Price__c.field-meta.xml
<CustomField>
    <fullName>Tether_Price__c</fullName>
    <description>Tether is a blockchain-based cryptocurrency whose cryptocoins in circulation are backed by an equivalent amount of traditional fiat currencies, like the dollar, the euro or the Japanese yen, which are held in a designated bank account. Tether tokens, the native tokens of the Tether network, trade under the USDT symbol.</description>
    <inlineHelpText>USDT</inlineHelpText>
    <label>Tether Price</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ScheduledCryptocurrency.cls
global class ScheduledCryptocurrency implements Schedulable, Database.AllowsCallouts {
    
	public static String CRON_EXP = '0 15 * * * ?';
    public static Decimal value = 1000000;

    global void execute(SchedulableContext SC) {
        requestData();
   	}
    
    @future(callout=true)
    public static void requestData(){
        HttpRequest request = new HttpRequest();
        // get this value from Setup -> Named Credentials
        request.setEndpoint('callout:Blockchain_info');
        request.setMethod('GET');
        try {
            HTTPResponse response = new Http().send(request);//need to handle exeption
            Decimal price = value / Decimal.valueOf(response.getBody());
            insert new Cryptocurrency__c(Tether_Price__c = price);
        } catch(Exception e){
            new Logger().log(e).saveLogs();
        }
    }
}